# Site settings
title: Grupo Política Social e Primeira Infância
email: lucia-garcia@uol.com.br
description: Grupo de Estudos sobre Desenvolvimento Social e Primeira Infância
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://infancia.ddns.net" # the base hostname & protocol for your site
twitter_username: primeirainfancia
github_username:  rodrigoesborges

# Build settings
markdown: kramdown
